name: MediBook Minimal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-frontend-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check frontend folder exists
        run: test -d frontend

      - name: Validate frontend package.json
        working-directory: frontend
        run: node -e "require('./package.json')"

      - name: Syntax check frontend JavaScript files
        working-directory: frontend
        run: |
          find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;

      - name: Check backend folder exists
        run: test -d backend

      - name: Validate backend package.json
        working-directory: backend
        run: node -e "require('./package.json')"

      - name: Syntax check backend JavaScript files
        working-directory: backend
        run: |
          find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;
